# Generated by Django 3.0.5 on 2020-04-22 11:49

from django.db import migrations


def create_data(apps, schema_editor):
    Contact = apps.get_model('contacts', 'Contact')
    Contact(name="Rahul", phone="00000000").save()

class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]


